### ISSUE TITLE
Game freezes when opening server selection screen.

### ISSUE THREAD

**Issue by wheredoesthislinkgo** [DarkKronicle/Glyphix#1]
When I click on the multiplayer button to open the server selection screen it opens the menu but then my game freezes. I removed Glyphix from my mods folder and it stopped. There was no crash report because the game didn't crash, but it froze and I had to force quit Minecraft. This only happened after the second time I opened the menu, the first time it worked fine.

**Comment by DarkKronicle** [comment]
Thanks for the report, seems like an infinite loop snuck by me somewhere... were there any emojis on the multiplayer screen?

**Comment by wheredoesthislinkgo** [comment]
No, but I do have Hypixel and MCCI on there with a lot of custom text, so that might be part of the problem
