### ISSUE TITLE
No idea how to use

### ISSUE THREAD

**Issue by Aces-and-Jacks** [DarkKronicle/Glyphix#2]
It's cool but I have no idea how to use this. The how to use section doesn't specify where to paste. There's no config. And when I do an emoji, for example :smile: or something nothing shows

However I'm aware that this mod is in beta so it isn't complete yet

**Comment by Scarlaid** [comment]
From what I know with this mod, it converts (some) Unicode into Twemoji(es)
![2022-12-17_22 27 01](https://user-images.githubusercontent.com/90851437/208249233-60f0d602-3681-4d0f-bfbe-d155b08a50ac.png)

You could get [Stendhal](https://www.curseforge.com/minecraft/mc-mods/stendhal) to have a whole board of Unicode like above
But use with choice, this mod broke color codes (following #3) so you will have to wait when they add supports for it in the future

**Comment by Aces-and-Jacks** [comment]
ok then, thanks
